### PR TITLE
fix a[tabindex=0]

### PR DESCRIPTION
**Pull request by afraser**
Fixes https://github.com/davidtheclark/tabbable/issues/2

### CODE REVIEW

**Comment by afraser** [comment]
@davidtheclark re: tests. This is barking at me about saucelabs credentials. Can you test it locally?

**Comment by davidtheclark** [comment]
Thanks @afraser! I'll look into it soon.

**Comment by afraser** [comment]
Thanks to you for sharing this code, good stuff.

**Comment by davidtheclark** [comment]
Merged in 82edb01c7aab4290a6dd585b8894ea6363c59d8d

**Comment by davidtheclark** [comment]
Published in 1.0.1

**Pull request closed without merging**
