### PR TITLE
add tabbables

### PR DESCRIPTION
**Pull request by GrosSacASac**
'video[controls]',
    'audio[controls]',
    'details>summary'

### CODE REVIEW

**Comment by davidtheclark** [comment]
@GrosSacASac Looks like tests are failing. Have you looked into that?

**Comment by GrosSacASac** [comment]
I saw it now

**Comment by davidtheclark** [comment]
@GrosSacASac: Ok, green light on existing tests. Can we have some new tests for the new feature, as well?

**Comment by GrosSacASac** [comment]
I don't have time

**Comment by davidtheclark** [comment]
Ok, maybe the next person who wants this feature will build it.

**Pull request closed without merging**
